(()=>{'use strict';const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion:reduce)');let media=[],current=0,paused=reduced.matches,gridMode=false,returnFocus=null;const dialog=$('lightbox');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const ratio=m=>Math.max(.72,Math.min(1.8,m.width/m.height));
function tile(m,i,clone=false,grid=false){const doc=m.id==='IMG_6735'||m.id.startsWith('71CA');return `<button class="scene${doc?' document':''}" data-index="${i}" style="--ratio:${ratio(m)}" aria-label="${esc(m.title)} (${i+1}/51)"${clone?' tabindex="-1"':''}>${m.type==='video'&&!grid?`<video poster="${m.thumb}" data-src="${m.src}" muted loop playsinline preload="none" aria-hidden="true"></video>`:`<img src="${m.thumb}" alt="" loading="lazy" decoding="async" width="${m.width}" height="${m.height}">`}${m.type==='video'?'<span class="video-mark">▶ VIDEO</span>':''}<span class="scene-caption">${esc(m.title)}</span></button>`;}
const videoObserver=new IntersectionObserver(entries=>{for(const e of entries){const v=e.target;if(e.isIntersecting&&!paused&&!dialog.open&&!gridMode&&!document.hidden){if(!v.src)v.src=v.dataset.src;v.play().catch(()=>{});}else v.pause();}},{rootMargin:'150px'});
function sync(){document.body.classList.toggle('paused',paused);$('pauseButton').setAttribute('aria-pressed',String(paused));$('pauseButton').textContent=paused?'흐름 재생':'일시정지';for(const v of $('reels').querySelectorAll('video')){const r=v.getBoundingClientRect();const onScreen=r.right>0&&r.left<innerWidth&&r.bottom>0&&r.top<innerHeight;if(!paused&&!dialog.open&&!gridMode&&!document.hidden&&onScreen){if(!v.src)v.src=v.dataset.src;v.play().catch(()=>{});}else v.pause();}}
function render(){const rows=[[],[],[]];media.forEach((m,i)=>rows[i%3].push({m,i}));$('reels').innerHTML=rows.map((row,n)=>{const contents=row.map(({m,i})=>tile(m,i)).join(''),clones=row.map(({m,i})=>tile(m,i,true)).join('');return `<div class="reel" aria-label="트립 장면 ${n+1}번째 줄"><div class="track" style="--duration:${[157,174,166][n]}s"><div class="group">${contents}</div><div class="group" aria-hidden="true">${clones}</div></div></div>`}).join('');$('grid').innerHTML=media.map((m,i)=>tile(m,i,false,true)).join('');$('reels').querySelectorAll('video').forEach(v=>videoObserver.observe(v));sync();}
function show(i){current=(i+media.length)%media.length;const m=media[current];$('mediaStage').replaceChildren();const element=document.createElement(m.type==='video'?'video':'img');element.src=m.src;if(m.type==='video'){element.controls=true;element.playsInline=true;element.poster=m.poster;element.autoplay=true;}else element.alt=m.title;const fail=()=>{const msg=document.createElement('p');msg.textContent='이 장면을 불러오지 못했어요. 다음 장면으로 이동해 주세요.';$('mediaStage').replaceChildren(msg);};element.addEventListener('error',fail,{once:true});$('mediaStage').append(element);$('sceneTitle').textContent=m.title;$('sceneCount').textContent=`${String(current+1).padStart(2,'0')} / ${media.length}  ${m.type==='video'?'VIDEO':'PHOTO'}`;}
function open(i,target){returnFocus=target;show(i);dialog.showModal();document.body.classList.add('modal-open');sync();$('closeButton').focus();}
document.addEventListener('click',e=>{const tile=e.target.closest('.scene');if(tile)open(Number(tile.dataset.index),tile);});$('closeButton').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{$('mediaStage').replaceChildren();document.body.classList.remove('modal-open');sync();returnFocus?.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});$('previousButton').onclick=()=>show(current-1);$('nextButton').onclick=()=>show(current+1);document.addEventListener('keydown',e=>{if(dialog.open&&!e.target.closest('video')){if(e.key==='ArrowLeft'){e.preventDefault();show(current-1);}if(e.key==='ArrowRight'){e.preventDefault();show(current+1);}}});
$('pauseButton').onclick=()=>{paused=!paused;sync();};$('viewButton').onclick=()=>{gridMode=!gridMode;$('grid').hidden=!gridMode;$('reels').hidden=gridMode;$('viewButton').setAttribute('aria-pressed',String(gridMode));$('viewButton').textContent=gridMode?'세 줄로 보기':'전체 51개 보기';$('pauseButton').hidden=gridMode;$('hint').textContent=gridMode?'사진과 영상 51개를 한눈에 살펴보세요':'장면을 누르면 크게 볼 수 있어요';sync();};$('fullButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('fullButton').textContent='전체화면 미지원';}};document.addEventListener('fullscreenchange',()=>{$('fullButton').textContent=document.fullscreenElement?'전체화면 종료':'전체화면';});document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',e=>{paused=e.matches;sync();});$('reels').addEventListener('focusin',e=>{const tile=e.target.closest('.scene');if(tile){paused=true;sync();tile.scrollIntoView({block:'nearest',inline:'center'});}});
async function load(){try{$('loadError').hidden=true;const r=await fetch('media.json?v=1');if(!r.ok)throw Error();media=await r.json();if(media.length!==51)throw Error();render();}catch{$('reels').innerHTML='';$('loadError').hidden=false;}}$('retryButton').onclick=load;load();})();
