const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
let records=[],plans=[],db=null,fb=null,shared=false;
const params=new URLSearchParams(location.search),siteQuery=params.get("site")||"";
function sum(items,key){return items.reduce((total,item)=>total+Number(item[key]||0),0)}
function group(items,key){return items.reduce((groups,item)=>{const value=item[key]||"미지정";(groups[value]||=[]).push(item);return groups},{})}
function activePlan(){return plans.find(plan=>plan.id===$("#plan-select").value)}
function filteredRecords(){
  const plan=activePlan(),region=$("#region-filter").value,q=$("#report-search").value.trim().toLowerCase();
  return records.filter(record=>(!plan||(record.date>=plan.start&&record.date<=plan.end&&(!plan.region||record.region===plan.region)))&&(!region||record.region===region)&&(!siteQuery||record.siteId===siteQuery)&&`${record.siteName} ${record.member} ${record.feedback}`.toLowerCase().includes(q));
}
function rankedRows(groups,labelKey="result"){
  const values=Object.entries(groups).map(([name,items])=>({name,items,total:sum(items,labelKey),avg:sum(items,labelKey)/items.length})).sort((a,b)=>b.total-a.total),max=Math.max(1,...values.map(item=>item.total));
  return values.map(item=>`<div class="rank-row"><div><b>${escapeHtml(item.name)}</b><span>${item.items.length}건 · AVG ${item.avg.toFixed(1)}</span></div><strong>${item.total}</strong><div class="mini-track"><i style="width:${Math.max(3,item.total/max*100)}%"></i></div></div>`).join("")||`<div class="report-empty">아직 기록이 없습니다.</div>`;
}
function render(){
  const items=filteredRecords(),plan=activePlan(),total=sum(items,"result"),goal=Number(plan?.goal||0),members=new Set(items.map(item=>item.member).filter(Boolean)),sites=group(items,"siteId");
  $("#overview-title").textContent=plan?.name||"전체 트립 결과";$("#plan-period").textContent=plan?`${plan.start} – ${plan.end} · ${plan.region} · ${plan.members}명 계획`:siteQuery?"선택한 사이트의 전체 기록":"저장된 현장 기록 전체";
  const percent=goal?Math.round(total/goal*100):0;$("#progress-percent").textContent=goal?`${percent}%`:"목표 미설정";$("#progress-bar").style.width=`${Math.min(100,percent)}%`;$(".progress-track").setAttribute("aria-valuenow",String(Math.min(100,percent)));
  $("#total-result").textContent=total;$("#goal-result").textContent=goal?goal.toLocaleString():"미설정";$("#member-count").textContent=`${members.size}명`;$("#overall-avg").textContent=items.length?(total/items.length).toFixed(1):"0.0";$("#site-count").textContent=`${Object.keys(sites).length}곳`;$("#record-count").textContent=`${items.length}건`;
  $("#daily-list").innerHTML=rankedRows(group(items,"date"));$("#member-list").innerHTML=rankedRows(group(items,"member"));
  $("#site-list").innerHTML=Object.values(sites).map(siteItems=>({items:siteItems,name:siteItems[0].siteName,total:sum(siteItems,"result")})).sort((a,b)=>b.total-a.total).map(site=>`<article class="site-report"><div><h3>${escapeHtml(site.name)}</h3><p>${site.items.length}건 · 총 결과 ${site.total}</p></div><strong>AVG ${(site.total/site.items.length).toFixed(1)}</strong><a href="./index.html#spots">사이트 카드에서 새 기록 남기기 →</a></article>`).join("")||`<div class="report-empty">사이트 결과가 쌓이면 이곳에서 AVG를 비교할 수 있습니다.</div>`;
  $("#record-list").innerHTML=[...items].sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date))).map(record=>`<article class="report-record"><time>${escapeHtml(record.date)}<br><small>${escapeHtml(record.member)}</small></time><div><h3>${escapeHtml(record.siteName)}</h3><p>${escapeHtml(record.feedback)}</p>${record.photoUrls?.length?`<div class="report-photos">${record.photoUrls.slice(0,4).map(url=>`<a href="${escapeHtml(url)}" target="_blank" rel="noreferrer"><img src="${escapeHtml(url)}" alt="실제 셋업사진" loading="lazy"></a>`).join("")}</div>`:""}</div><strong>결과 ${Number(record.result||0)}</strong></article>`).join("")||`<div class="report-empty">Trip 화면의 사이트 카드에서 첫 현장 기록을 남겨보세요.</div>`;$("#filtered-count").textContent=`${items.length}건`;
}
function renderControls(){
  const selected=$("#plan-select").value;$("#plan-select").innerHTML=`<option value="">전체 기록</option>${[...plans].sort((a,b)=>b.start.localeCompare(a.start)).map(plan=>`<option value="${escapeHtml(plan.id)}">${escapeHtml(plan.name)} · ${escapeHtml(plan.start)}</option>`).join("")}`;if(plans.some(plan=>plan.id===selected))$("#plan-select").value=selected;
  const region=$("#region-filter").value,regions=[...new Set([...plans.map(plan=>plan.region),...records.map(record=>record.region)].filter(Boolean))];$("#region-filter").innerHTML=`<option value="">전체 지역</option>${regions.map(name=>`<option>${escapeHtml(name)}</option>`).join("")}`;$("#region-filter").value=regions.includes(region)?region:"";
}
[$("#plan-select"),$("#region-filter")].forEach(el=>el.addEventListener("change",render));$("#report-search").addEventListener("input",render);
const dialog=$("#plan-dialog");$("#add-plan").addEventListener("click",()=>{$("#plan-form").reset();const today=new Date().toLocaleDateString("en-CA");$("#plan-start").value=today;$("#plan-end").value=today;$("#plan-members").value="10";$("#plan-daily-goal").value="3";dialog.showModal();document.body.style.overflow="hidden"});$("[data-close='plan']").addEventListener("click",()=>{dialog.close();document.body.style.overflow=""});
$("#plan-form").addEventListener("submit",async event=>{event.preventDefault();const id=`plan-${Date.now()}`,plan={id,name:$("#plan-name").value.trim(),start:$("#plan-start").value,end:$("#plan-end").value,region:$("#plan-region").value.trim(),members:Number($("#plan-members").value),goal:Number($("#plan-goal").value),dailyGoal:Number($("#plan-daily-goal").value),note:$("#plan-note").value.trim(),createdAt:new Date().toISOString()};if(plan.end<plan.start){$("#plan-message").textContent="종료일은 시작일보다 빠를 수 없습니다.";return}try{if(shared)await fb.set(fb.ref(db,`summerStrategy/tripPlans/${id}`),plan);else{plans.push(plan);localStorage.setItem("presence-trip-plans",JSON.stringify(plans));renderControls();$("#plan-select").value=id;render()}$("#plan-message").textContent="트립 일정과 목표를 저장했습니다.";setTimeout(()=>{dialog.close();document.body.style.overflow=""},600)}catch(error){$("#plan-message").textContent="저장하지 못했습니다. 연결을 확인해 주세요."}});
async function initFirebase(){const config={apiKey:"AIzaSyCYKKnK8myrSM-eip9HEJxYRq_hzpfPUY0",authDomain:"presence-team.firebaseapp.com",databaseURL:"https://presence-team-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"presence-team",storageBucket:"presence-team.firebasestorage.app",messagingSenderId:"1056684483470",appId:"1:1056684483470:web:1f50113d410b53458d3adf"};try{const [appApi,authApi,dbApi]=await Promise.all([import("https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/10.12.0/firebase-database.js")]);let app;try{app=appApi.getApp("presence-trip-reports")}catch(error){app=appApi.initializeApp(config,"presence-trip-reports")}const auth=authApi.getAuth(app);if(typeof auth.authStateReady==="function")await auth.authStateReady();if(!auth.currentUser)await authApi.signInAnonymously(auth);db=dbApi.getDatabase(app);fb=dbApi;shared=true;dbApi.onValue(dbApi.ref(db,".info/connected"),snap=>{const live=!!snap.val(),el=$("#sync-status");el.classList.toggle("live",live);el.querySelector("b").textContent=live?"Firebase 공용 동기화 ON":"오프라인";el.querySelector("span").textContent=live?"모든 팀원의 현장 기록과 목표가 실시간 반영됩니다.":"연결되면 공용 기록과 다시 맞춥니다."});dbApi.onValue(dbApi.ref(db,"summerStrategy/tripRecords"),snap=>{records=Object.values(snap.val()||{});renderControls();render()});dbApi.onValue(dbApi.ref(db,"summerStrategy/tripPlans"),snap=>{plans=Object.values(snap.val()||{});renderControls();render()})}catch(error){console.error(error);$("#sync-status").querySelector("b").textContent="오프라인 임시 저장"}}
records=JSON.parse(localStorage.getItem("presence-trip-records")||"[]");plans=JSON.parse(localStorage.getItem("presence-trip-plans")||"[]");renderControls();render();initFirebase();
