const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
let records=[],plans=[],assignments=[],customSites=[],db=null,fb=null,shared=false,selectedPlannerDate="",planChoiceInitialized=false;
const params=new URLSearchParams(location.search),siteQuery=params.get("site")||"";
function sum(items,key){return items.reduce((total,item)=>total+Number(item[key]||0),0)}
function group(items,key){return items.reduce((groups,item)=>{const value=item[key]||"미지정";(groups[value]||=[]).push(item);return groups},{})}
function activePlan(){return plans.find(plan=>plan.id===$("#plan-select").value)}
function dateRange(start,end){const days=[],cursor=new Date(`${start}T12:00:00`),last=new Date(`${end}T12:00:00`);while(cursor<=last&&days.length<31){days.push(cursor.toLocaleDateString("en-CA"));cursor.setDate(cursor.getDate()+1)}return days}
function plannerDates(){const plan=activePlan();if(plan)return dateRange(plan.start,plan.end);const today=new Date();return Array.from({length:4},(_,index)=>{const day=new Date(today);day.setDate(day.getDate()+index);return day.toLocaleDateString("en-CA")})}
function siteCatalog(){
  const plan=activePlan(),region=plan?.region||$("#region-filter").value,items=[];
  if(typeof gangneungDonghaeSites!=="undefined"&&(!region||/강릉|동해|삼척/.test(region)))items.push(...gangneungDonghaeSites.map(site=>({id:site.id,name:site.name,main:!!site.main,flow:site.flow||0})));
  if(typeof ctmRecords!=="undefined"&&(!region||/강릉|동해|삼척/.test(region)))items.push(...ctmRecords.map((site,index)=>({id:`ctm-plan-${index}`,name:site.name,main:false,flow:site.pAvg>=2?5:3})));
  items.push(...customSites.filter(site=>!region||site.region===region).map(site=>({id:site.id,name:site.name,main:!!site.main,flow:site.flow||0})),...records.filter(record=>!region||record.region===region).map(record=>({id:record.siteId,name:record.siteName,main:false,flow:0})),...assignments.map(item=>({id:item.siteId,name:item.siteName,main:false,flow:0})));
  return [...new Map(items.filter(item=>item.name).map(item=>[item.name,item])).values()].sort((a,b)=>Number(b.main)-Number(a.main)||b.flow-a.flow||a.name.localeCompare(b.name,"ko"));
}
function filteredRecords(){
  const plan=activePlan(),region=$("#region-filter").value,q=$("#report-search").value.trim().toLowerCase();
  return records.filter(record=>(!plan||(record.date>=plan.start&&record.date<=plan.end&&(!plan.region||record.region===plan.region)))&&(!region||record.region===region)&&(!siteQuery||record.siteId===siteQuery)&&`${record.siteName} ${record.member} ${record.feedback}`.toLowerCase().includes(q));
}
function rankedRows(groups,labelKey="result"){
  const values=Object.entries(groups).map(([name,items])=>({name,items,total:sum(items,labelKey),avg:sum(items,labelKey)/items.length})).sort((a,b)=>b.total-a.total),max=Math.max(1,...values.map(item=>item.total));
  return values.map(item=>`<div class="rank-row"><div><b>${escapeHtml(item.name)}</b><span>${item.items.length}건 · AVG ${item.avg.toFixed(1)}</span></div><strong>${item.total}</strong><div class="mini-track"><i style="width:${Math.max(3,item.total/max*100)}%"></i></div></div>`).join("")||`<div class="report-empty">아직 기록이 없습니다.</div>`;
}
function dayLabel(date){const value=new Date(`${date}T12:00:00`);return `${value.getMonth()+1}/${value.getDate()} (${["일","월","화","수","목","금","토"][value.getDay()]})`}
function assignmentsForDay(){const plan=activePlan();return assignments.filter(item=>item.date===selectedPlannerDate&&(!plan||item.planId===plan.id))}
function actualFor(assignment){return records.filter(record=>record.date===assignment.date&&record.member===assignment.member&&(record.siteId===assignment.siteId||record.siteName===assignment.siteName)).reduce((total,item)=>total+Number(item.result||0),0)}
function renderPlanner(){
  const days=plannerDates();if(!days.includes(selectedPlannerDate))selectedPlannerDate=days[0]||"";
  $("#planner-days").innerHTML=days.map(date=>`<button type="button" role="tab" aria-selected="${date===selectedPlannerDate}" class="${date===selectedPlannerDate?"active":""}" data-plan-date="${date}"><b>${dayLabel(date)}</b><span>${assignments.filter(item=>item.date===date&&(!activePlan()||item.planId===activePlan().id)).length}명</span></button>`).join("");
  const plan=activePlan(),dayItems=assignmentsForDay(),memberGroups=group(dayItems,"member"),conflicts=Object.values(memberGroups).filter(items=>items.length>1),siteGroups=group(dayItems,"siteName"),catalog=siteCatalog(),recommended=catalog.filter(site=>site.main).slice(0,8),laneNames=[...new Set(["미정",...Object.keys(siteGroups),...recommended.map(site=>site.name)])];
  $("#planned-members").textContent=`배치 ${new Set(dayItems.map(item=>item.member)).size}명`;$("#planned-sites").textContent=`사이트 ${new Set(dayItems.filter(item=>item.siteName!=="미정").map(item=>item.siteName)).size}곳`;$("#planned-goal").textContent=`일일 목표 ${sum(dayItems,"goal")}`;$("#planner-conflicts").textContent=conflicts.length?`⚠ 중복 ${conflicts.length}명`:"✓ 중복 없음";$("#planner-conflicts").classList.toggle("warning",conflicts.length>0);
  $("#site-options").innerHTML=`<option value="미정"></option>${catalog.map(site=>`<option value="${escapeHtml(site.name)}"></option>`).join("")}`;
  if(!plan){$("#planner-alert").textContent="먼저 위에서 트립 일정을 선택하거나 새 일정과 목표를 만들어 주세요.";$("#planner-alert").className="planner-alert show"}else if(conflicts.length){$("#planner-alert").textContent=`${conflicts.map(items=>items[0].member).join(", ")} 님이 같은 날 두 곳 이상에 배치되어 있습니다.`;$("#planner-alert").className="planner-alert show warning"}else{$("#planner-alert").textContent="사이트당 2–3명 배치를 권장합니다. PC에서는 사람 카드를 다른 사이트로 드래그할 수도 있어요.";$("#planner-alert").className="planner-alert show"}
  $("#planner-board").innerHTML=laneNames.map(name=>{const laneItems=siteGroups[name]||[],site=catalog.find(item=>item.name===name),over=laneItems.length>3;return `<section class="site-lane${name==="미정"?" unassigned":""}${over?" crowded":""}" data-drop-site="${escapeHtml(name)}"><header><div><span>${site?.main?"MAIN":"SITE"}</span><h3>${escapeHtml(name)}</h3></div><b>${laneItems.length}/3${over?" 초과":""}</b></header><div class="assignment-stack">${laneItems.map(item=>{const duplicate=(memberGroups[item.member]||[]).length>1,actual=actualFor(item);return `<article class="assignment-card role-${escapeHtml(item.role)}${duplicate?" duplicate":""}" draggable="true" data-assignment-id="${escapeHtml(item.id)}"><div><span>${item.role==="main"?"메인":item.role==="backup"?"예비":"서포트"}</span>${duplicate?`<i>중복</i>`:""}</div><h4>${escapeHtml(item.member)}</h4><p>목표 ${Number(item.goal||0)}${actual?` · <strong>결과 ${actual}</strong>`:""}</p>${item.note?`<small>${escapeHtml(item.note)}</small>`:""}<div class="assignment-actions"><button type="button" data-edit-assignment="${escapeHtml(item.id)}">변경</button><button type="button" data-next-assignment="${escapeHtml(item.id)}">다음날 복사</button></div></article>`}).join("")||`<button class="empty-lane" type="button" data-quick-site="${escapeHtml(name)}">＋ 이 사이트에 배치</button>`}</div></section>`}).join("");
}
function render(){
  const items=filteredRecords(),plan=activePlan(),total=sum(items,"result"),goal=Number(plan?.goal||0),members=new Set(items.map(item=>item.member).filter(Boolean)),sites=group(items,"siteId");
  $("#overview-title").textContent=plan?.name||"전체 트립 결과";$("#plan-period").textContent=plan?`${plan.start} – ${plan.end} · ${plan.region} · ${plan.members}명 계획`:siteQuery?"선택한 사이트의 전체 기록":"저장된 현장 기록 전체";
  const percent=goal?Math.round(total/goal*100):0;$("#progress-percent").textContent=goal?`${percent}%`:"목표 미설정";$("#progress-bar").style.width=`${Math.min(100,percent)}%`;$(".progress-track").setAttribute("aria-valuenow",String(Math.min(100,percent)));
  $("#total-result").textContent=total;$("#goal-result").textContent=goal?goal.toLocaleString():"미설정";$("#member-count").textContent=`${members.size}명`;$("#overall-avg").textContent=items.length?(total/items.length).toFixed(1):"0.0";$("#site-count").textContent=`${Object.keys(sites).length}곳`;$("#record-count").textContent=`${items.length}건`;
  $("#daily-list").innerHTML=rankedRows(group(items,"date"));$("#member-list").innerHTML=rankedRows(group(items,"member"));
  $("#site-list").innerHTML=Object.values(sites).map(siteItems=>({items:siteItems,name:siteItems[0].siteName,total:sum(siteItems,"result")})).sort((a,b)=>b.total-a.total).map(site=>`<article class="site-report"><div><h3>${escapeHtml(site.name)}</h3><p>${site.items.length}건 · 총 결과 ${site.total}</p></div><strong>AVG ${(site.total/site.items.length).toFixed(1)}</strong><a href="./index.html#spots">사이트 카드에서 새 기록 남기기 →</a></article>`).join("")||`<div class="report-empty">사이트 결과가 쌓이면 이곳에서 AVG를 비교할 수 있습니다.</div>`;
  $("#record-list").innerHTML=[...items].sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date))).map(record=>`<article class="report-record"><time>${escapeHtml(record.date)}<br><small>${escapeHtml(record.member)}</small></time><div><h3>${escapeHtml(record.siteName)}</h3><p>${escapeHtml(record.feedback)}</p>${record.photoUrls?.length?`<div class="report-photos">${record.photoUrls.slice(0,4).map(url=>`<a href="${escapeHtml(url)}" target="_blank" rel="noreferrer"><img src="${escapeHtml(url)}" alt="실제 셋업사진" loading="lazy"></a>`).join("")}</div>`:""}</div><strong>결과 ${Number(record.result||0)}</strong></article>`).join("")||`<div class="report-empty">Trip 화면의 사이트 카드에서 첫 현장 기록을 남겨보세요.</div>`;$("#filtered-count").textContent=`${items.length}건`;
  renderPlanner();
}
function renderControls(){
  const selected=$("#plan-select").value,sortedPlans=[...plans].sort((a,b)=>b.start.localeCompare(a.start));$("#plan-select").innerHTML=`<option value="">전체 기록</option>${sortedPlans.map(plan=>`<option value="${escapeHtml(plan.id)}">${escapeHtml(plan.name)} · ${escapeHtml(plan.start)}</option>`).join("")}`;if(plans.some(plan=>plan.id===selected))$("#plan-select").value=selected;else if(!planChoiceInitialized&&sortedPlans.length){$("#plan-select").value=sortedPlans[0].id;planChoiceInitialized=true}
  const region=$("#region-filter").value,regions=[...new Set([...plans.map(plan=>plan.region),...records.map(record=>record.region)].filter(Boolean))];$("#region-filter").innerHTML=`<option value="">전체 지역</option>${regions.map(name=>`<option>${escapeHtml(name)}</option>`).join("")}`;$("#region-filter").value=regions.includes(region)?region:"";
}
[$("#plan-select"),$("#region-filter")].forEach(el=>el.addEventListener("change",()=>{selectedPlannerDate="";render()}));$("#report-search").addEventListener("input",render);
const dialog=$("#plan-dialog"),assignmentDialog=$("#assignment-dialog");function openModal(modal){modal.showModal();document.body.style.overflow="hidden"}function closeModal(modal){modal.close();document.body.style.overflow=""}
$("#add-plan").addEventListener("click",()=>{$("#plan-form").reset();const today=new Date().toLocaleDateString("en-CA");$("#plan-start").value=today;$("#plan-end").value=today;$("#plan-members").value="10";$("#plan-daily-goal").value="3";openModal(dialog)});$("[data-close='plan']").addEventListener("click",()=>closeModal(dialog));$("[data-close='assignment']").addEventListener("click",()=>closeModal(assignmentDialog));
function openAssignment(id="",siteName=""){
  const plan=activePlan();if(!plan){$("#planner-alert").textContent="먼저 트립 일정을 선택해 주세요.";$("#planner-alert").className="planner-alert show warning";return}
  $("#assignment-form").reset();const item=assignments.find(value=>value.id===id);$("#assignment-id").value=item?.id||"";$("#assignment-title").textContent=item?"배치 빠르게 변경":"새 인원 배치";$("#assignment-date").value=item?.date||selectedPlannerDate||plan.start;$("#assignment-member").value=item?.member||"";$("#assignment-site").value=item?.siteName||siteName||"미정";$("#assignment-role").value=item?.role||"main";$("#assignment-goal").value=item?.goal??plan.dailyGoal??3;$("#assignment-note").value=item?.note||"";$("#delete-assignment").hidden=!item;$("#assignment-message").textContent="";openModal(assignmentDialog);
}
$("#add-assignment").addEventListener("click",()=>openAssignment());$("#planner-days").addEventListener("click",event=>{const button=event.target.closest("[data-plan-date]");if(!button)return;selectedPlannerDate=button.dataset.planDate;renderPlanner()});
async function saveAssignment(item){if(shared)await fb.set(fb.ref(db,`summerStrategy/tripAssignments/${item.id}`),item);else{const index=assignments.findIndex(value=>value.id===item.id);if(index>=0)assignments[index]=item;else assignments.push(item);localStorage.setItem("presence-trip-assignments",JSON.stringify(assignments));render()}}
async function removeAssignment(id){if(shared)await fb.remove(fb.ref(db,`summerStrategy/tripAssignments/${id}`));else{assignments=assignments.filter(item=>item.id!==id);localStorage.setItem("presence-trip-assignments",JSON.stringify(assignments));render()}}
$("#assignment-form").addEventListener("submit",async event=>{event.preventDefault();const plan=activePlan(),existing=assignments.find(item=>item.id===$("#assignment-id").value),siteName=$("#assignment-site").value.trim()||"미정",site=siteCatalog().find(item=>item.name===siteName),item={id:existing?.id||`assign-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,planId:plan.id,date:$("#assignment-date").value,member:$("#assignment-member").value.trim(),siteId:site?.id||`manual-${siteName.replace(/[^가-힣a-z0-9]/gi,"-")}`,siteName,role:$("#assignment-role").value,goal:Number($("#assignment-goal").value||0),note:$("#assignment-note").value.trim(),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};try{await saveAssignment(item);$("#assignment-message").textContent="배치를 저장했습니다.";selectedPlannerDate=item.date;setTimeout(()=>closeModal(assignmentDialog),450)}catch(error){$("#assignment-message").textContent="배치를 저장하지 못했습니다."}});
$("#delete-assignment").addEventListener("click",async()=>{const id=$("#assignment-id").value;if(!id)return;await removeAssignment(id);closeModal(assignmentDialog)});
$("#planner-board").addEventListener("click",async event=>{const edit=event.target.closest("[data-edit-assignment]");if(edit){openAssignment(edit.dataset.editAssignment);return}const quick=event.target.closest("[data-quick-site]");if(quick){openAssignment("",quick.dataset.quickSite);return}const next=event.target.closest("[data-next-assignment]");if(!next)return;const item=assignments.find(value=>value.id===next.dataset.nextAssignment),days=plannerDates(),index=days.indexOf(item.date);if(index<0||index===days.length-1){$("#planner-alert").textContent="트립 일정의 마지막 날이라 다음날로 복사할 수 없습니다.";$("#planner-alert").className="planner-alert show warning";return}const copy={...item,id:`assign-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,date:days[index+1],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await saveAssignment(copy);selectedPlannerDate=copy.date;render()});
$("#planner-board").addEventListener("dragstart",event=>{const card=event.target.closest("[data-assignment-id]");if(card)event.dataTransfer.setData("text/plain",card.dataset.assignmentId)});$("#planner-board").addEventListener("dragover",event=>{if(event.target.closest("[data-drop-site]"))event.preventDefault()});$("#planner-board").addEventListener("drop",async event=>{const lane=event.target.closest("[data-drop-site]"),id=event.dataTransfer.getData("text/plain"),item=assignments.find(value=>value.id===id);if(!lane||!item)return;event.preventDefault();const siteName=lane.dataset.dropSite,site=siteCatalog().find(value=>value.name===siteName);await saveAssignment({...item,siteName,siteId:site?.id||"unassigned",updatedAt:new Date().toISOString()})});
$("#copy-previous").addEventListener("click",async()=>{const plan=activePlan(),days=plannerDates(),index=days.indexOf(selectedPlannerDate);if(!plan||index<=0){$("#planner-alert").textContent="복사할 전날 배치가 없습니다.";$("#planner-alert").className="planner-alert show warning";return}const source=assignments.filter(item=>item.planId===plan.id&&item.date===days[index-1]);if(!source.length){$("#planner-alert").textContent="전날에 저장된 배치가 없습니다.";$("#planner-alert").className="planner-alert show warning";return}const copies=source.map((item,copyIndex)=>({...item,id:`assign-${Date.now()}-${copyIndex}`,date:selectedPlannerDate,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));if(shared){const updates={};copies.forEach(item=>updates[`summerStrategy/tripAssignments/${item.id}`]=item);await fb.update(fb.ref(db),updates)}else{assignments.push(...copies);localStorage.setItem("presence-trip-assignments",JSON.stringify(assignments));render()}$("#planner-alert").textContent=`전날 배치 ${copies.length}명을 복사했습니다. 필요한 사람이나 사이트만 변경하세요.`;$("#planner-alert").className="planner-alert show"});
$("#plan-form").addEventListener("submit",async event=>{event.preventDefault();const id=`plan-${Date.now()}`,plan={id,name:$("#plan-name").value.trim(),start:$("#plan-start").value,end:$("#plan-end").value,region:$("#plan-region").value.trim(),members:Number($("#plan-members").value),goal:Number($("#plan-goal").value),dailyGoal:Number($("#plan-daily-goal").value),note:$("#plan-note").value.trim(),createdAt:new Date().toISOString()};if(plan.end<plan.start){$("#plan-message").textContent="종료일은 시작일보다 빠를 수 없습니다.";return}try{if(shared)await fb.set(fb.ref(db,`summerStrategy/tripPlans/${id}`),plan);else{plans.push(plan);localStorage.setItem("presence-trip-plans",JSON.stringify(plans))}planChoiceInitialized=true;renderControls();$("#plan-select").value=id;selectedPlannerDate=plan.start;render();$("#plan-message").textContent="트립 일정과 목표를 저장했습니다.";setTimeout(()=>closeModal(dialog),600)}catch(error){$("#plan-message").textContent="저장하지 못했습니다. 연결을 확인해 주세요."}});
async function initFirebase(){const config={apiKey:"AIzaSyCYKKnK8myrSM-eip9HEJxYRq_hzpfPUY0",authDomain:"presence-team.firebaseapp.com",databaseURL:"https://presence-team-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"presence-team",storageBucket:"presence-team.firebasestorage.app",messagingSenderId:"1056684483470",appId:"1:1056684483470:web:1f50113d410b53458d3adf"};try{const [appApi,authApi,dbApi]=await Promise.all([import("https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/10.12.0/firebase-database.js")]);let app;try{app=appApi.getApp("presence-trip-reports")}catch(error){app=appApi.initializeApp(config,"presence-trip-reports")}const auth=authApi.getAuth(app);if(typeof auth.authStateReady==="function")await auth.authStateReady();if(!auth.currentUser)await authApi.signInAnonymously(auth);db=dbApi.getDatabase(app);fb=dbApi;shared=true;dbApi.onValue(dbApi.ref(db,".info/connected"),snap=>{const live=!!snap.val(),el=$("#sync-status");el.classList.toggle("live",live);el.querySelector("b").textContent=live?"Firebase 공용 동기화 ON":"오프라인";el.querySelector("span").textContent=live?"모든 팀원의 현장 기록·목표·배치가 실시간 반영됩니다.":"연결되면 공용 기록과 다시 맞춥니다."});dbApi.onValue(dbApi.ref(db,"summerStrategy/tripRecords"),snap=>{records=Object.values(snap.val()||{});renderControls();render()});dbApi.onValue(dbApi.ref(db,"summerStrategy/tripPlans"),snap=>{plans=Object.values(snap.val()||{});renderControls();render()});dbApi.onValue(dbApi.ref(db,"summerStrategy/tripAssignments"),snap=>{assignments=Object.values(snap.val()||{});render()});dbApi.onValue(dbApi.ref(db,"summerStrategy/tripSites"),snap=>{customSites=Object.values(snap.val()||{});renderPlanner()})}catch(error){console.error(error);$("#sync-status").querySelector("b").textContent="오프라인 임시 저장"}}
records=JSON.parse(localStorage.getItem("presence-trip-records")||"[]");plans=JSON.parse(localStorage.getItem("presence-trip-plans")||"[]");assignments=JSON.parse(localStorage.getItem("presence-trip-assignments")||"[]");customSites=JSON.parse(localStorage.getItem("presence-trip-sites")||"[]");renderControls();render();initFirebase();
