(()=>{'use strict';
const $=id=>document.getElementById(id),base='assets/revision-v10/',media=window.TRIP_MEDIA,reduced=matchMedia('(prefers-reduced-motion:reduce)');
const agenda=['트립의 목적','트립지역 선정하기','트립계획하기','트립운영하기','트립 후 피드백'];
const album=Array.from({length:29},(_,i)=>({src:base+`image${i+25}.jpeg`,title:`트립 장면 ${i+1}`}));
const first=[['IMG_5541','IMG_6703','IMG_4913','IMG_9909','IMG_4963'],['IMG_6636','IMG_6720','IMG_5561','IMG_6638','IMG_5441'],['IMG_4567','IMG_4872','IMG_6724','IMG_4845','IMG_4521']];
const used=new Set(first.flat()),rows=first.map(ids=>ids.map(id=>media.find(m=>m.id===id)));media.filter(m=>!used.has(m.id)).forEach((m,i)=>rows[i%3].push(m));
function filmRows(){return rows.map((r,i)=>`<div class="film-row"><div class="film-track" style="--duration:${[132,147,141][i]}s"><div class="film-group">${r.map(m=>`<img src="scenes/${m.thumb}" alt="" loading="lazy" decoding="async" style="--ratio:${Math.max(.74,Math.min(1.8,m.width/m.height))}" data-scene="${m.id}">`).join('')}</div><div class="film-group" aria-hidden="true">${r.map(m=>`<img src="scenes/${m.thumb}" alt="" loading="lazy" decoding="async" style="--ratio:${Math.max(.74,Math.min(1.8,m.width/m.height))}">`).join('')}</div></div></div>`).join('');}
$('introFilms').innerHTML=filmRows();
const photo=(file,caption,fit='contain')=>`<button class="photo ${fit}" data-image="${base+file}" data-caption="${caption}" aria-label="${caption} 크게 보기"><img src="${base+file}" alt="${caption}" draggable="false" decoding="async"></button>`;
const plans=Array.from({length:8},(_,i)=>({src:`assets/plan-examples-v11/example-${String(i+1).padStart(2,'0')}.png`,title:`팀원 계획 예시 ${String(i+1).padStart(2,'0')}`}));
const purposes=['인컴 극대화','배움의 기회','리프레시'];
const purposeMenu=active=>`<div class="purpose-menu">${purposes.map((t,i)=>`<p class="${active===i?'selected':''}">${t}</p>`).join('')}</div>`;
const shell=(title,section,body,cls='',dark=false)=>`<div class="slide-shell ${dark?'dark':''} ${cls}"><div class="slide-heading"><p class="section-label">${section?String(section).padStart(2,'0')+(title===agenda[section-1]?'':'　'+agenda[section-1]):'PRESENCE'}</p><h2>${title}</h2></div><div class="slide-body">${body}</div></div>`;
const reference=(title,section,file,caption)=>shell(title,section,`<div class="reference">${photo(file,caption)}</div>`,'reference-slide');
const planHighlights=[
 [{theme:'비 자연… 내가 이긴다!',score:'25 / 20 / 15',close:'180 / 150 / 120'}],
 [{theme:'PB 달성 · BEP 달성',score:'25 / 20 / 12',close:'175 / 140 / 84'}],
 [{theme:'PB 찍고 가기 · 즐겁게 배우기',score:'25 / 18 / 10',close:'170 / 130 / 70'}],
 [{theme:'다양하고 많은 경험',score:'20 / 15 / 10',close:'200 / 150 / 100'}],
 [{theme:'트립 부시기 · 팀 AVG 3.0 이상',score:'20 / 15 / 12',close:'150 / 125 / 100'},{theme:'BEP 돌파 · 팀 AVG 3.0 이상',score:'18 / 13 / 10',close:'125 / 90 / 70'}],
 [{theme:'KASH · PB 찍고 가기',score:'20 / 15 / 10',close:'170 / 130 / 85'},{theme:'MAINTAIN ATTITUDE',score:'20 / 15 / 12',close:'170 / 120 / 100'}],
 [{theme:'KASH · PB 찍고 가기',score:'20 / 15 / 10',close:'170 / 130 / 85'},{theme:'MAINTAIN ATTITUDE',score:'20 / 15 / 12',close:'160 / 120 / 100'}],
 [{theme:'PB 찍고 가기 · 즐겁게 배우기',score:'25 / 18 / 10',close:'170 / 130 / 70'},{theme:'다양하고 많은 경험',score:'20 / 15 / 10',close:'200 / 150 / 100'}]
];
function planReference(group){return shell('팀원 계획 예시',3,`<div class="plan-toolbar"><div class="plan-tabs" aria-label="계획 예시 묶음 선택">${[0,1].map(n=>`<button data-plan-group="${n}" aria-label="계획 예시 ${n*4+1}부터 ${n*4+4} 묶음 보기" aria-pressed="${group===n}">${n===0?'01–04':'05–08'}</button>`).join('')}</div><p>목표는 A / B / C 순 · 사진을 누르면 전체 내용</p></div><div class="plan-grid" role="region" aria-label="팀원 계획 예시 네 개 묶음" tabindex="0">${plans.slice(group*4,group*4+4).map((m,n)=>{const i=group*4+n;return `<article class="plan-card"><button class="plan-preview" data-plan="true" data-image="${m.src}" data-caption="${m.title}" aria-label="${m.title} 전체 내용 크게 보기"><img src="${m.src}" alt="${m.title}, 이름 모자이크 처리" decoding="async"><span>전체 보기 ↗</span></button><div class="plan-card-copy"><p class="plan-card-number">예시 ${String(i+1).padStart(2,'0')}</p><div class="plan-highlights">${planHighlights[i].map(h=>`<section class="plan-highlight"><h3>${h.theme}</h3><dl><div><dt>스코어</dt><dd>${h.score}</dd></div><div><dt>클로즈</dt><dd>${h.close}</dd></div></dl></section>`).join('')}</div></div></article>`;}).join('')}</div>`,'plan-example-slide',true);}
const pages=[
{title:'트립 운영 가이드',steps:['표지'],render:()=>`<div class="cover-slide"><p class="cover-brand">PRESENCE</p><div class="cover-copy"><h1>TRIP</h1><h2>운영 가이드</h2></div><img src="assets/trip-plane-clouds.png" alt="구름 사이를 날아가는 비행기" class="cover-plane"><p class="cover-footer">SECTOR LEADER</p></div>`},
{title:'아젠다',steps:['5개의 아젠다'],render:()=>`<div class="agenda-slide"><h2>아젠다</h2><ol>${agenda.map((t,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${t}</li>`).join('')}</ol></div>`},
{title:'트립의 목적',steps:['세 가지 목적','인컴 극대화','배움의 기회','함께 배우는 것','리프레시'],render:s=>{
const bodies=[`${purposeMenu(-1)}<div class="purpose-film-wrap"><div class="purpose-films">${filmRows()}</div><p class="film-caption">트립 장면들</p></div>`,`${purposeMenu(0)}<div class="pictograms">${[['image11.png','인컴'],['image12.png','필드시간'],['image13.svg','몰입']].map(([f,t],i)=>`<figure style="--delay:${i*.18}s"><img src="${base+f}" alt="${t}"><figcaption>${t}</figcaption></figure>`).join('')}</div>`,`${purposeMenu(1)}<div class="purpose-visual poster">${photo('learning-poster-revised.png','슬기로운 캠페이너 생활')}</div>`,`<div class="learning-list"><strong>COD</strong><strong>다양한 토픽</strong><strong>트립운영 방법</strong><strong>세일즈 TIP</strong><strong>네트워킹</strong></div>`,`${purposeMenu(2)}<div class="purpose-visual">${photo('image15.jpeg','함께 쉬어 가는 트립의 순간')}</div>`];
return shell(s===3?'함께 배우는 것':'트립의 목적',1,bodies[s],s===3?'learning-slide':s===2?'purpose-slide purpose-poster':'purpose-slide',true);}},
{title:'트립지역 선정하기',steps:['CTM 소통과 동료 피드백'],render:()=>shell('트립지역 선정하기',2,'<div class="two-stat"><div><strong>CTM</strong><p>소통 / 자료 요청</p></div><div><strong>동료</strong><p>경험 / 피드백</p></div></div>')},
{title:'날씨 확인',steps:['강수','예보'],render:s=>reference(s===0?'강수':'예보',2,s===0?'image16.png':'image17.png',s===0?'강수 지도 확인 예시':'지역별 일기 예보 확인 예시')},
{title:'트립계획하기',steps:['사이트 · 목표 · 개인 계획'],render:()=>shell('트립계획하기',3,`<div class="plan-list">${[['사이트 선정','CTM 자료 참고'],['목표 설정','Profit / Progress / People'],['개인 계획','테마 / 배움 / 약속']].map(([t,d],i)=>`<div><span>${i+1}</span><strong>${t}</strong><p>${d}</p></div>`).join('')}</div>`)},
{title:'CTM 자료 참고',steps:['자료 요청','사이트 자료'],render:s=>reference(s===0?'CTM 자료 요청':'사이트 자료 확인',3,s===0?'image19.png':'image18.png',s===0?'CTM에 군산 AVG 자료를 요청한 대화':'CTM이 공유한 군산 사이트 자료')},
{title:'사이트 선정',steps:['자료와 현장 확인'],render:()=>shell('사이트 선정',3,`<div class="site-list"><strong>CTM 자료</strong><strong>카카오맵</strong><strong>네이버지도</strong><strong>사용 가능 여부</strong></div><div class="site-photo">${photo('site-map-gangneung.png','네이버지도 강릉 다이소 사이트 선정 예시')}</div>`,'site-slide',true)},
{title:'트립 목표 설정',steps:['Best / Good / Minimum','계획 예시 01–04','계획 예시 05–08','목표 입력 예시'],render:s=>s===0?shell('트립 목표 설정',3,`<div class="abc">${[['A','Best','최고의 결과'],['B','Good','좋은 결과'],['C','Minimum','최소한의 결과']].map(([a,b,c])=>`<div><strong>${a}</strong><h3>${b}</h3><p>${c}</p></div>`).join('')}</div><p class="bottom-caption">스코어 / 클로즈 / 보상</p>`):s<=2?planReference(s-1):reference('나의 목표 세팅',3,'image22.png','트립 목표 입력 화면 예시')},
{title:'나의 트립계획',steps:['배움과 지킬 약속'],render:()=>shell('나의 트립계획',3,'<div class="personal-plan"><p class="person-name">임재영</p><h3>BEP 넘기고 오기<br><em>PB 찍고 가기</em></h3><div class="personal-details"><div><strong>배우고 싶은 것</strong><p>컨텍 / STP / 트립 운영</p></div><div><strong>지킬 약속</strong><p>필드시간 / 루틴 / 서로 신뢰</p></div></div></div>','personal-slide',true)},
{title:'트립 현황과 성과',steps:['트립 현황','팀 성과 기록'],render:s=>reference(s===0?'트립 현황':'팀 성과 기록',3,s===0?'image24.jpeg':'image23.jpeg',s===0?'26.08.04~07 강릉 트립 현황 기록':'NEWSKIN BULLETIN 팀 성과 기록')},
{title:'트립운영하기',steps:['요일별 테마','운영 기준'],render:s=>s===0?shell('트립운영하기',4,`<div class="week">${[['월','기강','첫날 집중'],['화','태도유지','첫날의 태도'],['수','액티비티','함께 재충전'],['목','PB 달성','최고 결과'],['금','빠벨','빠른 복귀']].map(([a,b,c])=>`<div><strong>${a}</strong><h3>${b}</h3><p>${c}</p></div>`).join('')}</div>`):shell('요일별 운영 기준',4,'<div class="criteria"><div><p>수요일</p><strong>19:00</strong><p>필드 종료</p><small>월·화 합산 팀 AVG 1.5 이상</small></div><div><p>금요일</p><strong>14~15시</strong><p>필드 종료 목표</p><small>0건인 팀원이 있으면 복귀 X</small></div></div>','criteria-slide',true)},
{title:'트립의 순간들',steps:Array.from({length:5},(_,i)=>`사진 ${i*6+1}–${Math.min(29,i*6+6)} / 29`),render:s=>shell('트립의 순간들',4,`<div class="album-grid">${album.slice(s*6,s*6+6).map(m=>`<button class="photo cover" data-image="${m.src}" data-caption="${m.title}" data-album="true" aria-label="${m.title} 크게 보기"><img src="${m.src}" alt="${m.title}" decoding="async"></button>`).join('')}</div>`,'album-slide',true)},
{title:'3일 트립이라면',steps:['기강 · 액티비티 · PB'],render:()=>shell('3일 트립이라면',4,`<div class="three-day"><strong>3</strong><div>${[['1일차','기강'],['2일차','액티비티'],['3일차','PB']].map(([a,b])=>`<p><span>${a}</span><b>${b}</b></p>`).join('')}</div></div>`)},
{title:'트립 후 피드백',steps:['챌린지와 윈'],render:()=>shell('트립 후 피드백',5,'<div class="two-stat feedback"><div><strong>챌린지</strong><p>어려웠던 점</p></div><div><strong>윈</strong><p>잘된 점</p></div></div>','',true)}
];
let page=0,step=0,paused=reduced.matches,notes={},imageItems=[],imageIndex=0,returnFocus=null;const noteKey='presence-trip-review-v12';try{const current=localStorage.getItem(noteKey),previous=localStorage.getItem('presence-trip-review-v11');notes=JSON.parse(current||previous||localStorage.getItem('presence-trip-review-v10')||'{}')||{};if(!current){const old={...notes};for(const k of Object.keys(notes))if(/^8-[1-9]$/.test(k))delete notes[k];if(previous){for(let g=0;g<2;g++){const entries=Array.from({length:4},(_,i)=>g*4+i+1).filter(i=>old[`8-${i}`]?.trim()).map(i=>`예시 ${String(i).padStart(2,'0')}\n${old[`8-${i}`]}`);if(entries.length)notes[`8-${g+1}`]=entries.join('\n\n');}if(old['8-9'])notes['8-3']=old['8-9'];}else{if(old['8-1'])notes['8-2']=old['8-1'];if(old['8-2'])notes['8-3']=old['8-2'];}}}catch{}
const stateKey=()=>`${page}-${step}`;
function syncFilms(){document.body.classList.toggle('films-paused',paused||document.hidden||$('tripScenes').open||$('imageViewer').open);$('pauseFilms').textContent=paused?'필름 재생':'필름 일시정지';$('pauseFilms').setAttribute('aria-pressed',String(paused));}
function show(p=page,s=0){page=Math.max(0,Math.min(pages.length-1,p));step=Math.max(0,Math.min(pages[page].steps.length-1,s));const d=pages[page],canvas=$('slideCanvas');canvas.innerHTML=d.render(step);canvas.dataset.page=String(page+1);canvas.dataset.step=String(step+1);canvas.classList.remove('entered');void canvas.offsetWidth;canvas.classList.add('entered');$('count').textContent=`${page+1} / ${pages.length}`;$('label').textContent=d.title;$('stepLabel').textContent=page===8&&step>=1&&step<=2?d.steps[step]:d.steps.length>1?`${d.steps[step]}　${step+1} / ${d.steps.length}`:d.steps[step];$('prev').disabled=page===0&&step===0;$('next').disabled=page===pages.length-1&&step===d.steps.length-1;$('purposeTools').hidden=!(page===2&&step===0);$('note').value=notes[stateKey()]||'';$('noteLabel').textContent=`${page+1}번 ${d.title} / ${d.steps[step]}`;$('fallback').hidden=true;document.querySelectorAll('.thumb').forEach((e,i)=>e.setAttribute('aria-current',String(page===i)));history.replaceState(null,'',`#slide-${page+1}-step-${step+1}`);syncFilms();}
function next(){if(step<pages[page].steps.length-1)show(page,step+1);else if(page<pages.length-1)show(page+1,0);}
function prev(){if(step>0)show(page,step-1);else if(page>0)show(page-1,pages[page-1].steps.length-1);}
$('next').onclick=next;$('prev').onclick=prev;
$('overview').innerHTML=pages.map((p,i)=>`<button class="thumb" data-page="${i}">${i===12?'<div class="overview-album">'+album.slice(0,6).map(m=>`<img src="${m.src}" alt="" loading="lazy">`).join('')+'</div>':`<img src="assets/overview-v10/${String(i+1).padStart(2,'0')}.png?v=20260915-v12" alt="" loading="lazy">`}<span>${String(i+1).padStart(2,'0')} ${p.title}${p.steps.length>1?' · '+p.steps.length+'단계':''}</span></button>`).join('');
$('overview').onclick=e=>{const b=e.target.closest('[data-page]');if(b){show(Number(b.dataset.page));window.scrollTo({top:0,behavior:'instant'});}};
$('present').onclick=()=>{document.body.classList.add('presenting');window.scrollTo({top:0,behavior:'instant'});};$('exitPresentation').onclick=()=>document.body.classList.remove('presenting');
$('note').oninput=()=>{notes[stateKey()]=$('note').value;try{localStorage.setItem(noteKey,JSON.stringify(notes));$('saved').textContent='이 브라우저에 저장했습니다.';}catch{$('saved').textContent='메모를 복사해 보관해 주세요.';}};
$('copy').onclick=async()=>{const text=Object.entries(notes).filter(([,v])=>v.trim()).map(([k,v])=>{const [p,s]=k.split('-').map(Number);return `${p+1}번 ${pages[p].title} / ${pages[p].steps[s]}\n${v}`;}).join('\n\n');try{await navigator.clipboard.writeText(text);$('saved').textContent='전체 메모를 복사했습니다.';}catch{$('allNotes').value=text;$('fallback').hidden=false;$('allNotes').select();}};
$('pauseFilms').onclick=()=>{paused=!paused;syncFilms();};
$('showScenes').onclick=()=>{$('sceneFrame').src='scenes/index.html?embed=1&v=20260915-v10';$('tripScenes').showModal();syncFilms();};$('closeScenes').onclick=()=>$('tripScenes').close();$('tripScenes').addEventListener('close',()=>{$('sceneFrame').src='about:blank';syncFilms();$('showScenes').focus({preventScroll:true});});
function showImage(i){imageIndex=Math.max(0,Math.min(imageItems.length-1,i));const m=imageItems[imageIndex];$('largeImage').src=m.src;$('largeImage').alt=m.title;$('imageCaption').textContent=m.title;$('imageOriginal').href=m.src;$('imageCount').textContent=imageItems.length>1?`${imageIndex+1} / ${imageItems.length}`:'';$('imagePrev').hidden=$('imageNext').hidden=imageItems.length===1;$('imagePrev').disabled=imageIndex===0;$('imageNext').disabled=imageIndex===imageItems.length-1;}
$('slideCanvas').onclick=e=>{const choice=e.target.closest('[data-plan-group]');if(choice){show(8,Number(choice.dataset.planGroup)+1);return;}const b=e.target.closest('[data-image]');if(!b)return;returnFocus=b;imageItems=b.dataset.plan?plans:b.dataset.album?album:[{src:b.dataset.image,title:b.dataset.caption}];$('readImage').hidden=!b.dataset.plan;$('imageViewer').classList.remove('reading-image');$('readImage').textContent='확대해서 읽기';$('readImage').setAttribute('aria-pressed','false');showImage(imageItems.findIndex(i=>i.src===b.dataset.image));$('imageViewer').showModal();syncFilms();};
$('readImage').onclick=()=>{const on=$('imageViewer').classList.toggle('reading-image');$('readImage').textContent=on?'화면에 맞추기':'확대해서 읽기';$('readImage').setAttribute('aria-pressed',String(on));};
$('closeImage').onclick=()=>$('imageViewer').close();$('imagePrev').onclick=()=>showImage(imageIndex-1);$('imageNext').onclick=()=>showImage(imageIndex+1);$('imageViewer').addEventListener('close',()=>{syncFilms();returnFocus?.focus({preventScroll:true});});
document.addEventListener('keydown',e=>{if(e.metaKey||e.ctrlKey||e.altKey||/TEXTAREA|INPUT/.test(e.target.tagName)||!$('tripIntro').hidden||$('tripScenes').open)return;if($('imageViewer').open){if(e.key==='ArrowRight'){e.preventDefault();showImage(imageIndex+1);}if(e.key==='ArrowLeft'){e.preventDefault();showImage(imageIndex-1);}return;}if(e.key==='ArrowRight'){e.preventDefault();next();}else if(e.key==='ArrowLeft'){e.preventDefault();prev();}else if(e.key==='Home'){e.preventDefault();show(0);}else if(e.key==='End'){e.preventDefault();show(pages.length-1);}else if(e.key==='Escape')document.body.classList.remove('presenting');});
let tx=0,ty=0;$('slideCanvas').addEventListener('touchstart',e=>{tx=e.touches[0].clientX;ty=e.touches[0].clientY;},{passive:true});$('slideCanvas').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-tx,dy=e.changedTouches[0].clientY-ty;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)(dx<0?next:prev)();},{passive:true});
document.addEventListener('visibilitychange',syncFilms);reduced.addEventListener('change',e=>{paused=e.matches;syncFilms();});window.addEventListener('trip-start',()=>show(0));window.addEventListener('hashchange',()=>{const route=location.hash.match(/^#slide-(\d+)(?:-step-(\d+))?$/);if(route){$('tripIntro').hidden=true;$('deck').hidden=false;document.body.classList.remove('intro-active');show(Number(route[1])-1,route[2]?Number(route[2])-1:0);}});const m=location.hash.match(/^#slide-(\d+)(?:-step-(\d+))?$/);show(m?Number(m[1])-1:0,m?.[2]?Number(m[2])-1:0);
})();
